import React,{useMemo,useState} from "react";
import {createRoot} from "react-dom/client";
import {Search,Heart,MapPin,GraduationCap,Users,Home,MessageCircle,User,Plus,CheckCircle2,Menu,X,ChevronRight,ShieldCheck,BedDouble,SlidersHorizontal,Send} from "lucide-react";
import "./styles.css";

const universities=["Université de Tunis El Manar","Université de Carthage","Université de Tunis","Université de La Manouba","Université de Sousse","Université de Sfax","Université de Monastir"];
const faculties=["FST","FSEGT","INSAT","ISG","ISET","ENIT","IHEC"];
const properties=[
 {id:1,title:"S+3 moderne — El Manar",area:"El Manar",uni:"Université de Tunis El Manar",faculty:"FST",price:750,rooms:3,available:1,distance:.8,walk:10,furnished:true,owner:"Ahmed Property",verified:true,img:"https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=1000&q=80",amenities:["WiFi","Climatisation","Meublé"]},
 {id:2,title:"S+2 étudiant — El Menzah",area:"El Menzah",uni:"Université de Tunis El Manar",faculty:"FST",price:620,rooms:2,available:1,distance:.6,walk:8,furnished:true,owner:"Sami",verified:true,img:"https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?auto=format&fit=crop&w=1000&q=80",amenities:["WiFi","Meublé"]},
 {id:3,title:"Studio — Centre Urbain Nord",area:"Centre Urbain Nord",uni:"Université de Tunis El Manar",faculty:"INSAT",price:500,rooms:1,available:1,distance:1.2,walk:15,furnished:true,owner:"Dar Student",verified:true,img:"https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=1000&q=80",amenities:["WiFi","Climatisation"]},
 {id:4,title:"S+4 partagé — Ariana",area:"Ariana",uni:"Université de Carthage",faculty:"IHEC",price:900,rooms:4,available:2,distance:1.5,walk:19,furnished:true,owner:"Moez",verified:false,img:"https://images.unsplash.com/photo-1600566753086-00f18fb6b3ea?auto=format&fit=crop&w=1000&q=80",amenities:["Balcon","Meublé","Machine à laver"]},
 {id:5,title:"S+2 — Le Bardo",area:"Le Bardo",uni:"Université de La Manouba",faculty:"ISET",price:580,rooms:2,available:1,distance:1.0,walk:12,furnished:false,owner:"Maison Bardo",verified:true,img:"https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1000&q=80",amenities:["Parking","Balcon"]}
];
const roommate=[
 {id:1,name:"Youssef",uni:"Université de Tunis El Manar",faculty:"FST",area:"El Manar",budget:"250–350 TND",smoke:"Non-fumeur",style:"Calme",match:93,img:"https://i.pravatar.cc/120?img=12"},
 {id:2,name:"Ahmed",uni:"Université de Tunis El Manar",faculty:"INSAT",area:"El Menzah",budget:"200–300 TND",smoke:"Non-fumeur",style:"Sociable",match:89,img:"https://i.pravatar.cc/120?img=33"},
 {id:3,name:"Malek",uni:"Université de Carthage",faculty:"IHEC",area:"Ariana",budget:"250–400 TND",smoke:"Non-fumeur",style:"Calme",match:86,img:"https://i.pravatar.cc/120?img=47"}
];

function App(){
 const [page,setPage]=useState("home"),[role,setRole]=useState("student"),[selected,setSelected]=useState(null),[favorites,setFavorites]=useState([]),[mobile,setMobile]=useState(false),[search,setSearch]=useState({uni:"",faculty:"",budget:1000}),[query,setQuery]=useState("");
 const [roommates,setRoommates]=useState(roommate);
 const filtered=useMemo(()=>properties.filter(p=>(!search.uni||p.uni===search.uni)&&(!search.faculty||p.faculty===search.faculty)&&p.price<=Number(search.budget||99999)&&(!query||p.title.toLowerCase().includes(query.toLowerCase())||p.area.toLowerCase().includes(query.toLowerCase()))),[search,query]);
 const nav=(p)=>{setPage(p);setMobile(false);window.scrollTo(0,0)};
 return <div className="app">
  <header><div className="nav"><button className="brand" onClick={()=>nav("home")}><span className="logo"><Home size={19}/></span><span>Campus<span>Dar</span></span></button>
   <div className="desktop-nav"><button className={page==="search"?"active":""} onClick={()=>nav("search")}>Trouver un logement</button><button className={page==="roommates"?"active":""} onClick={()=>nav("roommates")}>Trouver un colocataire</button><button onClick={()=>nav("owner")}>Publier un logement</button></div>
   <div className="nav-right"><button className="role" onClick={()=>setRole(role==="student"?"owner":"student")}>{role==="student"?"🎓 Étudiant":"🏠 Propriétaire"}</button><button className="login" onClick={()=>nav("dashboard")}>Connexion</button><button className="hamb" onClick={()=>setMobile(!mobile)}>{mobile?<X/>:<Menu/>}</button></div>
  </div>{mobile&&<div className="mobile-menu"><button onClick={()=>nav("search")}>Trouver un logement</button><button onClick={()=>nav("roommates")}>Trouver un colocataire</button><button onClick={()=>nav("owner")}>Publier un logement</button><button onClick={()=>nav("dashboard")}>Mon espace</button></div>}</header>

  {page==="home"&&<HomePage nav={nav} search={search} setSearch={setSearch}/>}
  {page==="search"&&<SearchPage data={filtered} search={search} setSearch={setSearch} query={query} setQuery={setQuery} open={(p)=>{setSelected(p);nav("property")}} fav={favorites} toggleFav={id=>setFavorites(f=>f.includes(id)?f.filter(x=>x!==id):[...f,id])}/>}
  {page==="property"&&selected&&<PropertyPage p={selected} nav={nav} fav={favorites.includes(selected.id)} toggle={()=>setFavorites(f=>f.includes(selected.id)?f.filter(x=>x!==selected.id):[...f,selected.id])}/>}
  {page==="roommates"&&<RoommatePage data={roommates} nav={nav}/>}
  {page==="owner"&&<OwnerPage nav={nav}/>}
  {page==="dashboard"&&<Dashboard nav={nav}/>}
  <footer><div><b>Campus<span>Dar</span></b><p>Le logement étudiant, simplifié pour la Tunisie.</p></div><div><b>Explorer</b><p onClick={()=>nav("search")}>Logements</p><p onClick={()=>nav("roommates")}>Colocataires</p></div><div><b>Pour les propriétaires</b><p onClick={()=>nav("owner")}>Publier un logement</p></div><div><b>© 2026 CampusDar</b><p>Tunisie</p></div></footer>
 </div>
}

function HomePage({nav,search,setSearch}){return <main>
 <section className="hero"><div className="hero-copy"><div className="pill"><GraduationCap size={16}/> Pensé pour les étudiants tunisiens</div><h1>Ton logement étudiant.<br/><em>Ton campus.</em> Ta coloc.</h1><p>Découvre des logements près de ton université et trouve les colocataires qui te correspondent.</p>
 <div className="searchbox"><label>🎓 Où étudies-tu ?</label><select value={search.uni} onChange={e=>setSearch({...search,uni:e.target.value})}><option value="">Toutes les universités</option>{universities.map(x=><option key={x}>{x}</option>)}</select><select value={search.faculty} onChange={e=>setSearch({...search,faculty:e.target.value})}><option value="">Toutes les facultés</option>{faculties.map(x=><option key={x}>{x}</option>)}</select><select value={search.budget} onChange={e=>setSearch({...search,budget:e.target.value})}><option value="500">≤ 500 TND</option><option value="700">≤ 700 TND</option><option value="1000">≤ 1000 TND</option></select><button onClick={()=>nav("search")}><Search size={18}/> Rechercher</button></div>
 <button className="secondary-cta" onClick={()=>nav("roommates")}><Users size={18}/> J'ai trouvé un logement, je cherche des colocataires <ChevronRight size={17}/></button></div>
 <div className="hero-art"><div className="float-card top"><span className="check"><CheckCircle2 size={17}/></span><div><b>94% match</b><small>FST · 8 min à pied</small></div></div><img src="https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?auto=format&fit=crop&w=1200&q=80"/><div className="float-card bottom"><div className="avatars"><img src="https://i.pravatar.cc/50?img=12"/><img src="https://i.pravatar.cc/50?img=33"/><img src="https://i.pravatar.cc/50?img=47"/></div><div><b>2 colocataires trouvés</b><small>pour cet appartement</small></div></div></div></section>
 <section className="section"><div className="section-head"><div><span className="eyebrow">DÉCOUVRE</span><h2>Les logements populaires</h2></div><button className="linkbtn" onClick={()=>nav("search")}>Voir tout <ChevronRight size={16}/></button></div><div className="cards">{properties.slice(0,3).map(p=><PropertyCard key={p.id} p={p} open={()=>nav("search")}/>)}</div></section>
 <section className="how"><div><span className="eyebrow">SIMPLE</span><h2>De l'université à ton nouveau chez-toi.</h2></div><div className="steps"><Step n="01" icon={<GraduationCap/>} t="Choisis ton campus" d="Dis-nous où tu étudies et ton budget."/><Step n="02" icon={<Home/>} t="Trouve ton logement" d="Compare les logements par distance et prix."/><Step n="03" icon={<Users/>} t="Trouve ta coloc" d="Rejoins une coloc ou crée ton groupe." /></div></section>
 </main>}

function Step({n,icon,t,d}){return <div className="step"><div className="step-icon">{icon}</div><small>{n}</small><h3>{t}</h3><p>{d}</p></div>}

function SearchPage({data,search,setSearch,query,setQuery,open,fav,toggleFav}){return <main className="page"><div className="page-title"><div><span className="eyebrow">LOGEMENTS</span><h1>Près de ton campus</h1><p>{data.length} logements correspondent à ta recherche.</p></div><button className="filter-mobile"><SlidersHorizontal size={17}/> Filtres</button></div><div className="search-layout"><aside><b>Filtres</b><label>Recherche<input value={query} onChange={e=>setQuery(e.target.value)} placeholder="El Manar, Ariana..."/></label><label>Université<select value={search.uni} onChange={e=>setSearch({...search,uni:e.target.value})}><option value="">Toutes</option>{universities.map(x=><option key={x}>{x}</option>)}</select></label><label>Faculté<select value={search.faculty} onChange={e=>setSearch({...search,faculty:e.target.value})}><option value="">Toutes</option>{faculties.map(x=><option key={x}>{x}</option>)}</select></label><label>Budget max<select value={search.budget} onChange={e=>setSearch({...search,budget:e.target.value})}><option value="500">500 TND</option><option value="700">700 TND</option><option value="1000">1000 TND</option></select></label><div className="checkline"><input type="checkbox"/> Meublé</div><div className="checkline"><input type="checkbox"/> Chambre disponible</div></aside><section><div className="resultbar"><span>Meilleur match</span><button>Plus proche de l'université ▾</button></div><div className="cards grid">{data.map(p=><PropertyCard key={p.id} p={p} open={()=>open(p)} fav={fav.includes(p.id)} toggle={()=>toggleFav(p.id)}/>)}</div></section><div className="mapfake"><MapPin size={28}/><b>Carte</b><span>Les positions apparaîtront ici avec Mapbox/Google Maps.</span>{data.map((p,i)=><div key={p.id} className="pin" style={{left:`${20+i*16}%`,top:`${25+(i%3)*20}%`}}>{p.price} TND</div>)}</div></div></main>}

function PropertyCard({p,open,fav,toggle}){return <article className="property-card"><div className="photo"><img src={p.img}/>{p.verified&&<span className="verified"><ShieldCheck size={14}/> Vérifié</span>}<button className="heart" onClick={e=>{e.stopPropagation();toggle?.()}}><Heart size={18} fill={fav?"currentColor":"none"}/></button></div><div className="pc-body"><div className="row"><h3>{p.title}</h3><b>{p.price} <small>TND</small></b></div><p className="muted"><MapPin size={14}/> {p.area}</p><div className="stats"><span>🛏 {p.rooms} ch.</span><span>🎓 {p.distance} km</span><span>🚶 {p.walk} min</span></div><div className="match"><span>94% match</span><span>{p.available} chambre{p.available>1?"s":""} disponible{p.available>1?"s":""}</span></div><button className="fullbtn" onClick={open}>Voir le logement <ChevronRight size={16}/></button></div></article>}

function PropertyPage({p,nav,fav,toggle}){return <main className="page"><button className="back" onClick={()=>nav("search")}>← Retour aux logements</button><div className="detail"><div className="detail-gallery"><img src={p.img}/><div><img src={p.img}/><img src={p.img}/></div></div><div className="detail-info"><div className="eyebrow">LOGEMENT VÉRIFIÉ</div><h1>{p.title}</h1><p className="bigprice">{p.price} TND <small>/ mois</small></p><p className="muted"><MapPin size={16}/> {p.area} · {p.distance} km de {p.faculty}</p><div className="detail-badges"><span>🎓 {p.distance} km de {p.faculty}</span><span>🚶 {p.walk} min à pied</span><span>🛏 {p.rooms} chambres</span></div><hr/><h3>Équipements</h3><div className="amenities">{p.amenities.map(a=><span key={a}>✓ {a}</span>)}</div><hr/><h3>Chambres</h3><div className="rooms"><div><b>Chambre 1</b><span className="occupied">Occupée</span></div><div><b>Chambre 2</b><span className="occupied">Occupée</span></div><div><b>Chambre 3</b><span className="available">Disponible · {Math.round(p.price/p.rooms)} TND</span></div></div><div className="actions"><button className="primary" onClick={()=>alert("Demande envoyée !")}>Postuler</button><button className="outline" onClick={()=>nav("roommates")}><Users size={17}/> Trouver des colocataires</button><button className="iconbtn" onClick={toggle}><Heart size={18} fill={fav?"currentColor":"none"}/></button></div></div></div></main>}

function RoommatePage({data,nav}){return <main className="page"><div className="page-title"><div><span className="eyebrow">COLOCATION</span><h1>Trouve ta coloc.</h1><p>Des étudiants qui cherchent quelqu'un avec qui partager leur logement.</p></div><button className="primary" onClick={()=>alert("Formulaire de demande de colocataire — à connecter à Supabase.")}><Plus size={18}/> J'ai besoin d'une coloc</button></div><div className="roommate-hero"><div><h2>Tu as déjà trouvé un appart ?</h2><p>Publie ton besoin et laisse les étudiants compatibles venir à toi.</p><button className="secondary-cta" onClick={()=>alert("Création de demande de colocataire.")}>Créer une demande <ChevronRight size={17}/></button></div><Users size={80}/></div><div className="room-grid">{data.map(r=><article className="room-card" key={r.id}><div className="room-top"><img src={r.img}/><span>{r.match}% match</span></div><h3>{r.name}</h3><p>{r.faculty} · {r.uni.replace("Université de ","")}</p><div className="room-tags"><span>📍 {r.area}</span><span>💰 {r.budget}</span><span>🚭 {r.smoke}</span><span>🧹 {r.style}</span></div><button className="fullbtn" onClick={()=>alert(`Message à ${r.name}`)}>Contacter <MessageCircle size={16}/></button></article>)}</div></main>}

function OwnerPage({nav}){return <main className="page"><div className="owner-hero"><div><span className="eyebrow">POUR LES PROPRIÉTAIRES</span><h1>Louez votre logement aux étudiants.</h1><p>Publiez votre appartement, gérez les chambres et trouvez des étudiants près de leur campus.</p><button className="primary" onClick={()=>nav("dashboard")}><Plus size={18}/> Ajouter un logement</button></div><div className="owner-stats"><b>2 194</b><span>logements actifs</span><b>12 843</b><span>demandes étudiantes</span></div></div><div className="owner-flow"><Step n="01" icon={<Home/>} t="Publiez" d="Ajoutez votre logement et ses chambres."/><Step n="02" icon={<Users/>} t="Recevez" d="Les étudiants compatibles postulent."/><Step n="03" icon={<CheckCircle2/>} t="Louez" d="Choisissez vos futurs locataires." /></div></main>}

function Dashboard({nav}){return <main className="page"><div className="dash-head"><div><span className="eyebrow">MON ESPACE</span><h1>Bonjour, Ahmed 👋</h1><p>Voici ce qui se passe avec tes recherches.</p></div><button className="primary" onClick={()=>nav("owner")}><Plus size={18}/> Publier un logement</button></div><div className="kpis"><div><Home/><b>12</b><span>Logements sauvegardés</span></div><div><Users/><b>3</b><span>Matches coloc</span></div><div><MessageCircle/><b>7</b><span>Messages</span></div><div><Send/><b>2</b><span>Candidatures</span></div></div><section className="dashboard-section"><div className="section-head"><div><span className="eyebrow">RECOMMANDÉS</span><h2>Pour toi</h2></div><button className="linkbtn" onClick={()=>nav("search")}>Voir tout <ChevronRight size={16}/></button></div><div className="cards">{properties.slice(0,3).map(p=><PropertyCard key={p.id} p={p} open={()=>nav("search")}/>)}</div></section></main>}

createRoot(document.getElementById("root")).render(<App/>);
